### ISSUE TITLE
Kinect2Grabber.hpp Can't find!

### ISSUE THREAD

**Issue by jiaojialulu** [giacomodabisias/kinectv2CalibrationCapture#1]
where can I get "Kinect2Grabber.hpp"?Thank you!

**Comment by giacomodabisias** [comment]
There is no such file. That is the old version of the grabber

2015-10-19 7:39 GMT+02:00 jiaojialulu notifications@github.com:

> where can I get "Kinect2Grabber.hpp"?Thank you!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/giacomodabisias/kinectv2CalibrationCapture/issues/1.

## 

G. Dabisias, PhD Student
PERCRO, (Laboratory of Perceptual Robotics)
Scuola Superiore Sant'Anna
via Luigi Alamanni 13D, San Giuliano Terme 56010 (PI), Italy
mob.: +39 3480839095

**Comment by jiaojialulu** [comment]
so,this "kinectv2CalibrationCapture" can't run?

**Comment by cforntu** [comment]
Yes, I want to ask the same question, can this kinectv2CalibrationCapture run

**Comment by giacomodabisias** [comment]
Hi,
The new libfreenect2 api extracts directly all the calibration parameters. 
If you want to calibrate it by yourself you just need to update that code with the new grabber in my github repo.
I will do it in the next days by myself probably.

**Comment by cforntu** [comment]
Hi, could you tell me how could I find the new grabber.
  Regards,

**Comment by giacomodabisias** [comment]
https://github.com/giacomodabisias/libfreenect2pclgrabber

Il 20 Lug 2016 04:41, "cforntu" notifications@github.com ha scritto:

**Comment by giacomodabisias** [comment]
Hi,
fixed everything
